
package:
    name: nifty
    version: v1.0.7

source:
  path: ..

build:
  number: 6

requirements:
  build:
    - cmake
    - {{ compiler("cxx")}}
  host:
    - python {{ python }}
    - boost-cpp {{ boost }}
    - numpy {{ numpy }}
    - xtensor >=0.19,<0.20
    - xtensor-python >=0.22,<0.23
    - nlohmann_json
    - blosc  # [not win]
    - bzip2  # [not win]
    - zlib  # [not win]
    - z5py {{ z5py }} # [not win]
    - vigra
    # - bzip2

  run:
    - python
    - {{ pin_compatible("boost-cpp") }}
    - {{ pin_compatible("numpy") }}
    - {{ pin_compatible("z5py") }}
    - scikit-image
    - vigra
    - blosc  # [not win]
    - bzip2  # [not win]
    - zlib  # [not win]

test:
    imports:
      - nifty
    source_files:
      - src/python/test/graph/*.py
    commands:
      - python -m unittest discover -s src/python/test -v

about:
  home: https://github.com/DerThorsten/nifty
  license: MIT
  summary: Graph-based segmentation algorithms
